import os
import time
from pathlib import Path
from fpdf import FPDF

STATIC_EXPORTS_DIR = Path("static/exports")
STATIC_EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

class ComicPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 8, 'ComicCraft - AI Comic Story Creator', 0, 1, 'C')
        self.line(10, 18, 200, 18)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def save_pdf(layout: list, comic_title: str = "ComicCraft_Story") -> str:
    """
    Milestone 2 - Activity 2.1: Export Comic Panel and Story into PDF.
    Compiles the full comic into a multi-page PDF using FPDF.
    Each panel's title, image, and narration are placed neatly on separate pages.
    """
    pdf = ComicPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    timestamp = int(time.time())
    safe_title = "".join(c for c in comic_title if c.isalnum() or c in (' ', '_', '-')).rstrip()
    pdf_filename = f"Comic_{safe_title}_{timestamp}.pdf".replace(" ", "_")
    output_path = STATIC_EXPORTS_DIR / pdf_filename

    # Cover Page
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.ln(30)
    pdf.cell(0, 15, comic_title, 0, 1, "C")
    pdf.set_font("Helvetica", "I", 14)
    pdf.cell(0, 10, "Generated by ComicCraft AI Engine", 0, 1, "C")
    pdf.ln(20)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 8, f"This personalized comic features {len(layout)} panels of AI-generated storytelling and illustration.")

    # Panel Pages
    for panel in layout:
        pdf.add_page()
        # Panel Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, f"{panel.get('title', 'Panel')}", 0, 1, "L")
        pdf.ln(3)

        # Image if exists
        img_rel = panel.get("image_path", "")
        # Resolve to local path
        local_img = img_rel.lstrip("/")
        if os.path.exists(local_img):
            try:
                pdf.image(local_img, x=20, y=pdf.get_y(), w=170)
                pdf.ln(115)
            except Exception as e:
                print(f"Failed to place image {local_img} in PDF: {e}")

        # Scene description (italics)
        pdf.set_font("Helvetica", "I", 11)
        pdf.multi_cell(0, 6, f"Scene: {panel.get('scene_description', '')}")
        pdf.ln(3)

        # Caption & Dialogue
        pdf.set_font("Helvetica", "B", 11)
        if panel.get("dialogue"):
            pdf.multi_cell(0, 6, f"Dialogue: {panel.get('dialogue')}")
        if panel.get("caption"):
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, f"Narration: {panel.get('caption')}")

        # Prompt Reference
        pdf.ln(4)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, f"Image Prompt: {panel.get('image_prompt', '')}")
        pdf.set_text_color(0, 0, 0)

    pdf.output(str(output_path))
    return f"/static/exports/{pdf_filename}"
