import { jsPDF } from "jspdf";
import { ComicLayout } from "../types/comic.js";

/**
 * Milestone 2 & Scenario 3: Compiles comic layout into a beautiful multi-page PDF
 * with Cover Page, Panel Illustrations, Dialogue Bubbles, and Narration.
 */
export async function generateComicPdf(comic: ComicLayout): Promise<string> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Helper to add dark comic border around the page
  const addPageBorder = () => {
    doc.setDrawColor(17, 24, 39);
    doc.setLineWidth(1.5);
    doc.rect(8, 8, pageWidth - 16, pageHeight - 16);
    doc.setLineWidth(0.5);
    doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  };

  // ===================== PAGE 1: COVER PAGE =====================
  addPageBorder();

  // Header Banner
  doc.setFillColor(250, 204, 21); // Bright comic yellow
  doc.rect(10, 10, pageWidth - 20, 32, "F");
  doc.setDrawColor(17, 24, 39);
  doc.setLineWidth(1);
  doc.line(10, 42, pageWidth - 10, 42);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(220, 38, 38);
  doc.text("COMICCRAFT PRESENTS", pageWidth / 2, 24, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text("COLLECTOR'S EDITION • ISSUE #1 • ALL-NEW ADVENTURE", pageWidth / 2, 34, { align: "center" });

  // Main Comic Title
  doc.setFontSize(26);
  doc.setTextColor(17, 24, 39);
  const titleLines = doc.splitTextToSize(comic.title.toUpperCase(), pageWidth - 40);
  doc.text(titleLines, pageWidth / 2, 65, { align: "center" });

  // Decorative divider
  doc.setDrawColor(245, 158, 11);
  doc.setLineWidth(1.2);
  doc.line(30, 80, pageWidth - 30, 80);

  // Comic Details Box
  doc.setFillColor(254, 243, 199);
  doc.roundedRect(20, 90, pageWidth - 40, 60, 4, 4, "F");
  doc.setDrawColor(17, 24, 39);
  doc.setLineWidth(0.8);
  doc.roundedRect(20, 90, pageWidth - 40, 60, 4, 4, "D");

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text("STORY SPECIFICATIONS", 25, 102);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`★ Main Hero: ${comic.character_name}`, 25, 112);
  doc.text(`★ Setting: ${comic.setting}`, 25, 120);
  doc.text(`★ Tone: ${comic.story_tone}`, 25, 128);
  doc.text(`★ Visual Art Style: ${comic.art_style}`, 25, 136);
  doc.text(`★ Total Comic Panels: ${comic.panels.length} Full Panels`, 25, 144);

  // Prompt & Synopsis Box
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("PROMPT SYNOPSIS", 20, 165);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const promptLines = doc.splitTextToSize(`"${comic.story_prompt}"`, pageWidth - 40);
  doc.text(promptLines, 20, 173);

  if (comic.full_story_narration) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(17, 24, 39);
    doc.text("THE EPIC NARRATIVE", 20, 200);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(55, 65, 81);
    const storyLines = doc.splitTextToSize(comic.full_story_narration, pageWidth - 40);
    doc.text(storyLines.slice(0, 10), 20, 208);
  }

  // Cover Footer
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`GENERATED BY COMICCRAFT AI • ${new Date(comic.created_at).toLocaleDateString()}`, pageWidth / 2, pageHeight - 16, { align: "center" });

  // ===================== PANEL PAGES =====================
  for (let i = 0; i < comic.panels.length; i++) {
    const panel = comic.panels[i];
    doc.addPage();
    addPageBorder();

    // Panel Header Badge
    doc.setFillColor(250, 204, 21);
    doc.rect(10, 10, pageWidth - 20, 18, "F");
    doc.setDrawColor(17, 24, 39);
    doc.setLineWidth(0.8);
    doc.line(10, 28, pageWidth - 10, 28);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(17, 24, 39);
    doc.text(`PANEL ${panel.panel_number} OF ${comic.panels.length}: ${panel.title.toUpperCase()}`, 16, 22);

    if (panel.sound_effect) {
      doc.setFillColor(239, 68, 68);
      doc.roundedRect(pageWidth - 45, 12, 32, 14, 2, 2, "F");
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text(panel.sound_effect, pageWidth - 29, 21, { align: "center" });
    }

    // Artwork Area
    let currentY = 34;
    const imgWidth = pageWidth - 40;
    const imgHeight = 95;

    try {
      if (panel.image_url && panel.image_url.startsWith("data:image")) {
        // Can add SVG / PNG data directly
        doc.addImage(panel.image_url, "PNG", 20, currentY, imgWidth, imgHeight);
      } else {
        // Draw decorative panel canvas frame with title
        doc.setFillColor(30, 41, 59);
        doc.roundedRect(20, currentY, imgWidth, imgHeight, 3, 3, "F");
        doc.setDrawColor(17, 24, 39);
        doc.setLineWidth(1.2);
        doc.roundedRect(20, currentY, imgWidth, imgHeight, 3, 3, "D");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(16);
        doc.setTextColor(250, 204, 21);
        doc.text(panel.title, pageWidth / 2, currentY + 45, { align: "center" });

        doc.setFontSize(11);
        doc.setTextColor(226, 232, 240);
        doc.text(`[ ${comic.art_style} Illustration ]`, pageWidth / 2, currentY + 55, { align: "center" });
      }
    } catch (e) {
      console.warn("Could not draw image into PDF:", e);
    }

    // Outer border around image
    doc.setDrawColor(17, 24, 39);
    doc.setLineWidth(1.5);
    doc.rect(20, currentY, imgWidth, imgHeight);

    currentY += imgHeight + 8;

    // Scene Description in Italics
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10.5);
    doc.setTextColor(75, 85, 99);
    const sceneLines = doc.splitTextToSize(`Scene: ${panel.scene_description}`, pageWidth - 40);
    doc.text(sceneLines, 20, currentY);
    currentY += sceneLines.length * 5 + 4;

    // Dialogue Speech Balloon
    if (panel.dialogue) {
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(17, 24, 39);
      doc.setLineWidth(1);
      doc.roundedRect(20, currentY, pageWidth - 40, 22, 4, 4, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(17, 24, 39);
      const dialogueLines = doc.splitTextToSize(`💬 ${panel.dialogue}`, pageWidth - 48);
      doc.text(dialogueLines, 24, currentY + 9);
      currentY += 28;
    }

    // Narration / Ambient Caption Box
    if (panel.caption) {
      doc.setFillColor(254, 243, 199);
      doc.setDrawColor(217, 119, 6);
      doc.setLineWidth(0.8);
      doc.roundedRect(20, currentY, pageWidth - 40, 18, 2, 2, "FD");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(31, 41, 55);
      const captionLines = doc.splitTextToSize(`📜 Narration: ${panel.caption}`, pageWidth - 48);
      doc.text(captionLines, 24, currentY + 8);
      currentY += 24;
    }

    // Prompt Reference Note at bottom
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    const promptRefLines = doc.splitTextToSize(`Artistic Prompt Reference: ${panel.image_prompt}`, pageWidth - 40);
    doc.text(promptRefLines, 20, pageHeight - 22);

    // Footer Page Number
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.text(`Page ${i + 2} of ${comic.panels.length + 1}`, pageWidth / 2, pageHeight - 12, { align: "center" });
  }

  // Save as blob URL and trigger download
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);

  // Trigger browser download
  const filename = comic.pdf_filename || `ComicCraft_${comic.character_name}.pdf`;
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  return url;
}
